### ISSUE TITLE
Security vulnerability in transitive dependency deep-object-diff

### ISSUE THREAD

**Issue by AndreasPresthammer** [equinor/fusion-components#1548]
Vulnerability CVE report: https://www.cve.org/CVERecord?id=CVE-2022-41713

Dependency comes in through the following dependency chains:

Introduced through: @equinor/fusion-components@2.5.28 › @storybook/addon-jest@6.4.19 › @storybook/theming@6.4.19 › deep-object-diff@1.1.7
Introduced through: @equinor/fusion-components@2.5.28 › @storybook/addon-jest@6.4.19 › @storybook/api@6.4.19 › @storybook/theming@6.4.19 › deep-object-diff@1.1.7
Introduced through: @equinor/fusion-components@2.5.28 › @storybook/addon-jest@6.4.19 › @storybook/addons@6.4.19 › @storybook/theming@6.4.19 › deep-object-diff@1.1.7

**Comment by odinr** [comment]
this code is not compile with the Fusion Components, only used for documentation and development.
Since the components in this library is set to move to Fusion-React-Components we wont prioritise to update storybook.

we might delete the jest dep from the library from the package, since it is not in use
